spring:
  datasource:
    url: jdbc:h2:mem:testDb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml